#+TITLE: Brice NÉDELEC
#+DATE: [2021-03-11 Jeu]
#+AUTHOR: chat-wane
#+EMAIL: grumpy dot chat dot wane at gmail dot com

#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/style.css" />
#+HTML_HEAD: <script src="js/main.js"></script>

* About

Let me introduce myself: my name is Brice Nédelec; and this is my
personal page, that is, mostly an elaborated curriculum vitae.

In 2016, I obtained a Ph.D in computer science from the [[https://www.univ-nantes.fr/][University of
Nantes]] in France under the supervision of Pr. [[https://sites.google.com/view/pascal-molli][Pascal Molli]], and
Pr. [[https://www.univ-nantes.fr/achour-mostefaoui][Achour Mostéfaoui]]; and with the helpful advice of Dr. [[https://www.univ-nantes.fr/emmanuel-desmontils][Emmanuel
Desmontils]] in early stages. The topic was about giving back their
ownership to authors of documents by decentralizing the collaborative
editing done in Web browsers.

My research interests include, but are not limited to, communication,
consistency, and causality. While these topics mostly originate from
my Ph.D about decentralized collaborative editors, I am deeply
interested in the broader theme of distributed protocols. I like to
understand, extract, and abstract the pieces that compose a
middleware. Overall, I am just interested in solving puzzles.

Since forever, my personal interests expand to all sorts of arts. My
trinity consists in music, painting, and gaming, for, at times, I
strum some strings and wipe some brushes.

* Education


** To make some additional testsststst
** Woof

* Experience
* Publications
* Skills

